### PR TITLE
support definition of equalisation release time

### PR DESCRIPTION
**Pull request by Falcosc**

### CODE REVIEW

**Comment by Falcosc** [comment]
@aerawk @sejkii @xShooerman @BoGnY @KomithEr
I did add a possibility to configure release time (how fast audio levels will be adjusted)

The Windows slider goes from 2 to 7 while 2 is the fastest one.
It is technical possible to set 1 and 0 there, but I find it difficult to identify if 1 actually does anything better then 2.

Could you try it out? Depending on your test result I will either limit the input to 2-7 or allow values below 2

Here is the direct link to the updated file:
https://raw.githubusercontent.com/Falcosc/enable-loudness-equalisation/releasetime/EnableLoudness.ps1

example would be 
```
./EnableLoudness.ps1 -releaseTime 2
```
vs
```
./EnableLoudness.ps1 -releaseTime 1
```

In the File Changed Tab, you will also see my adjustments to the README file. Please give me some feedback about that as well. Thank you

**Comment by aerawk** [comment]
@Falcosc 
The first time I tried running the updated script, I got an error saying that `releaseTime` was an unknown parameter. It looks like the script you have set up for the easy copy/paste under the How to Download and Run section only points to `main` in the url, so it would be good to add another copy/paste script that points to the `releasetime` branch. 

After changing that, I ran the script with the `-releaseTime 2` flag and I got the _"Loudness Settings don't need to be enabled message."_ I ran it again with `-releaseTime 1` and it seemingly ran successfully. I may not get a good chance to test it out for a couple of days, but wanted to give you this update for now.

**Comment by Falcosc** [comment]
Thank you, I will just wait for that.

You did check the branch more thoroughly than expected: the README needs to match the main branch, because after merge it becomes the main branch. That's why the old links are correct in the new README.

But here the copy paste block for the pullrequest:

```
Invoke-WebRequest https://raw.githubusercontent.com/Falcosc/enable-loudness-equalisation/releasetime/EnableLoudness.ps1 -OutFile $env:HOMEPATH\EnableLoudness.ps1
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
. $env:HOMEPATH\EnableLoudness.ps1 -releaseTime 1

```

**Comment by Falcosc** [comment]
@aerawk @sejkii @xShooerman @BoGnY @KomithEr
Does -releaseTime 1 vs -releaseTime 2 make any difference on your side? It's hard to tell on my side.

**Comment by aerawk** [comment]
@Falcosc 
It's also hard for me to say one way or the other. I tested it out for a while last night and I'm not sure that I can perceive any difference.

**Pull request merged**
